name: ProxyStopper
main: com.ne0nx3r0.ProxyStopper.ProxyStopper
version: '0.1'
database: false
description: Attempts to fight (public) proxies
commands:
   ps:
      description: Proxy stopper commands